# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi

unset rc

_confdir=${XDG_CONFIG_HOME:-$HOME/.config}/bash
_datadir=${XDG_DATA_HOME:-$HOME/.local/share}/bash

[[ -r "$_confdir/bashrc" ]] && . "$_confdir/bashrc"

[[ ! -d "$_datadir" ]] && mkdir -p "$_datadir"
HISTFILE=$_datadir/history

unset _confdir
unset _datadir

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi

#add additional folders to PATH
#PATH=$PATH:/home/pieter/.local/pycharm-community-2022.2.3/bin

export PATH

set -o vi

shopt -s autocd

bind -m vi-insert "Control-l: clear-screen"
alias setkbbe="setxkbmap -model pc105 -layout be -variant oss -option ''"
alias setkbus="setxkbmap -model pc105 -layout us -variant intl -option ''"
alias setkbusintl="setxkbmap -layout us -variant altgr-intl -option nodeadkeys"

alias i="sudo dnf install "
alias s="dnf search "
alias t="tmux"
alias tls="tmux ls"
alias tns="tmux new -s"
alias tat="tmux attach -t"
alias ll="ls -la"
cl()
{
    cd $@
    ls
}
alias cdu="cd .. && ll"
alias r="ranger"
alias v="nvim "
alias vim="nvim "
alias vvimrc="vimx ~/.vimrc"
alias vbash="nvim ~/.bashrc"
alias p="python3 "
alias pyfo="cd ~/Documents/Coderen/Python/"
alias bin="cd ~/.local/bin/"
alias jour="journalctl -r"
alias po="udisksctl power-off -b" #followed by eg: /dev/sdb
alias contoserver="ssh -L 8888:ubuntu-server-tp:5432 pieter@192.168.1.14"
alias wgu="sudo wg-quick up peer1"
alias wgd="sudo wg-quick down peer1"
alias wtr="curl wttr.in"
alias pm="passmenu"
alias tfa="terraform apply -auto-approve"
alias tfd="terraform destroy -auto-approve"

source ~/.bash_prompt
#export PYENV_ROOT="$HOME/.pyenv"
#command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
#eval "$(pyenv init -)"

